### ISSUE TITLE
请问能提供transpath的vit_small预训练好的模型吗

### ISSUE THREAD

**Issue by irsLu** [Xiyue-Wang/TransPath#7]
我对您们的工作非常感兴趣， 但是在复现过程遇到很多问题，我看只是提供了moco的vit_small，请问能提供transpath的vit_small的预训练好的模型嘛

**Comment by irsLu** [comment]
或者在单个节点，多gpu上怎么运行预训练脚本呢？ 我按照指令运行会报错。报错信息如下：
Traceback (most recent call last):
  File "/share/home/luoyang/miniconda3/envs/MAE/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/share/home/luoyang/TransPath/main_byol_transpath.py", line 251, in main_worker
    train(train_loader, model, criterion, optimizer, epoch, args)
  File "/share/home/luoyang/TransPath/main_byol_transpath.py", line 296, in train
    loss = model(images[0],images[1])
  File "/share/home/luoyang/miniconda3/envs/MAE/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/share/home/luoyang/miniconda3/envs/MAE/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 929, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/share/home/luoyang/miniconda3/envs/MAE/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/share/home/luoyang/TransPath/byol_pytorch/byol_pytorch_get_feature.py", line 217, in forward
    if return_embedding:
RuntimeError: Boolean value of Tensor with more than one value is ambiguous

**Comment by irsLu** [comment]
> 或者在单个节点，多gpu上怎么运行预训练脚本呢？ 我按照指令运行会报错。报错信息如下： Traceback (most recent call last): File "/share/home/luoyang/miniconda3/envs/MAE/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap fn(i, *args) File "/share/home/luoyang/TransPath/main_byol_transpath.py", line 251, in main_worker train(train_loader, model, criterion, optimizer, epoch, args) File "/share/home/luoyang/TransPath/main_byol_transpath.py", line 296, in train loss = model(images[0],images[1]) File "/share/home/luoyang/miniconda3/envs/MAE/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl return forward_call(*input, **kwargs) File "/share/home/luoyang/miniconda3/envs/MAE/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 929, in forward output = self.module(*inputs[0], **kwargs[0]) File "/share/home/luoyang/miniconda3/envs/MAE/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl return forward_call(*input, **kwargs) File "/share/home/luoyang/TransPath/byol_pytorch/byol_pytorch_get_feature.py", line 217, in forward if return_embedding: RuntimeError: Boolean value of Tensor with more than one value is ambiguous

我发现您的代码存在一些问题，比如这个问题是模型的forward第二个参数是bool，而传进去的是两张图像
